name: flutter_baidu_mob_stat
description: 百度统计插件。
version: 1.2.6
repository: https://github.com/miaozhenkun/fl_baidu_mob_stat_ys

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: fl.baidu.mob.stat
        pluginClass: BaiduMobStatPlugin
      ios:
        pluginClass: BaiduMobStatPlugin
